<?php
$title = 'Editar uma indicação de tratamento';
$this->headTitle($title);
?>
<div class="row">
    <div class="col-md-12">
        <h1><?=$title?></h1>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <?php
            $form = $this->form;
            $form->setAttribute('action', 
                    $this->url('tratamento_indicacoes/edit', ['id' => $id]));
            $form->prepare();
            echo $this->form()->openTag($form);
            echo $this->formHidden($form->get('id'));
            echo $this->formRow($form->get('nome'));
            echo '<br>';
            echo $this->formRow($form->get('descricao'));
            echo '<br>';
            echo $this->formSubmit($form->get('submit'));
            echo $this->form()->closeTag();
        ?>
    </div>
</div>




