<?php
$title = 'Deletar um tratamento';
$this->headTitle($title);
?>
<div class="row">
    <div class="col-md-12">
        <h1><?=$title?></h1>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <?php
        $urlDelete = $this->url('tratamentos', 
                ['action' => 'delete', 'id' => $tratamento->id]);
        ?>
        <form name="delete" action="<?=$urlDelete?>" method="post">
            <p>Você realmente quer deletar o tratamento:</p>
            <p><?=$tratamento->id.' '.$tratamento->nome?></p>
            <button type="submit" name="delete" value="S" class="btn btn-danger">Deletar</button>
            <button type="submit" name="delete" value="N" class="btn btn-default">Cancelar</button>
        </form>
    </div>
</div>

