-- MySQL Script generated by MySQL Workbench
-- 05/30/16 10:19:34
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema passaro
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `passaro` ;

-- -----------------------------------------------------
-- Schema passaro
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `passaro` DEFAULT CHARACTER SET utf8 ;
USE `passaro` ;

-- -----------------------------------------------------
-- Table `passaro`.`especie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `passaro`.`especie` ;

CREATE TABLE IF NOT EXISTS `passaro`.`especie` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `passaro`.`passaro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `passaro`.`passaro` ;

CREATE TABLE IF NOT EXISTS `passaro`.`passaro` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `especie_id` INT UNSIGNED NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `data_entrada` DATETIME NOT NULL,
  `data_saida` DATETIME NULL,
  `data_nascimento` DATETIME NULL,
  `data_falecimento` DATETIME NULL,
  `sexo` CHAR(1) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_passaro_especie_idx` (`especie_id` ASC),
  CONSTRAINT `fk_passaro_especie`
    FOREIGN KEY (`especie_id`)
    REFERENCES `passaro`.`especie` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `passaro`.`tratamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `passaro`.`tratamento` ;

CREATE TABLE IF NOT EXISTS `passaro`.`tratamento` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `passaro`.`passaro_tratamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `passaro`.`passaro_tratamento` ;

CREATE TABLE IF NOT EXISTS `passaro`.`passaro_tratamento` (
  `passaro_id` INT UNSIGNED NOT NULL,
  `tratamento_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`passaro_id`, `tratamento_id`),
  INDEX `fk_passaro_tratamento_tratamento1_idx` (`tratamento_id` ASC),
  INDEX `fk_passaro_tratamento_passaro1_idx` (`passaro_id` ASC),
  CONSTRAINT `fk_passaro_tratamento_passaro1`
    FOREIGN KEY (`passaro_id`)
    REFERENCES `passaro`.`passaro` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_passaro_tratamento_tratamento1`
    FOREIGN KEY (`tratamento_id`)
    REFERENCES `passaro`.`tratamento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `passaro`.`periodo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `passaro`.`periodo` ;

CREATE TABLE IF NOT EXISTS `passaro`.`periodo` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(100) NULL,
  `data_inicio` DATETIME NOT NULL,
  `data_fim` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `passaro`.`indicacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `passaro`.`indicacao` ;

CREATE TABLE IF NOT EXISTS `passaro`.`indicacao` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `passaro`.`periodo_indicacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `passaro`.`periodo_indicacao` ;

CREATE TABLE IF NOT EXISTS `passaro`.`periodo_indicacao` (
  `periodo_id` INT UNSIGNED NOT NULL,
  `indicacao_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`periodo_id`, `indicacao_id`),
  INDEX `fk_periodo_indicacao_indicacao1_idx` (`indicacao_id` ASC),
  INDEX `fk_periodo_indicacao_periodo1_idx` (`periodo_id` ASC),
  CONSTRAINT `fk_periodo_indicacao_periodo1`
    FOREIGN KEY (`periodo_id`)
    REFERENCES `passaro`.`periodo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_periodo_indicacao_indicacao1`
    FOREIGN KEY (`indicacao_id`)
    REFERENCES `passaro`.`indicacao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `passaro`.`tratamento_periodo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `passaro`.`tratamento_periodo` ;

CREATE TABLE IF NOT EXISTS `passaro`.`tratamento_periodo` (
  `tratamento_id` INT UNSIGNED NOT NULL,
  `periodo_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`tratamento_id`, `periodo_id`),
  INDEX `fk_tratamento_periodo_periodo1_idx` (`periodo_id` ASC),
  INDEX `fk_tratamento_periodo_tratamento1_idx` (`tratamento_id` ASC),
  CONSTRAINT `fk_tratamento_periodo_tratamento1`
    FOREIGN KEY (`tratamento_id`)
    REFERENCES `passaro`.`tratamento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tratamento_periodo_periodo1`
    FOREIGN KEY (`periodo_id`)
    REFERENCES `passaro`.`periodo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `passaro`.`tratamento_duracao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `passaro`.`tratamento_duracao` ;

CREATE TABLE IF NOT EXISTS `passaro`.`tratamento_duracao` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `qtde_dia` TINYINT UNSIGNED NOT NULL,
  `qtde_vezes_dia` TINYINT UNSIGNED NOT NULL,
  `hora_inicio_dia` TIME NOT NULL,
  `qtde_folga_dia` TINYINT NULL,
  `repete` TINYINT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `passaro`.`tratamento_dosagem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `passaro`.`tratamento_dosagem` ;

CREATE TABLE IF NOT EXISTS `passaro`.`tratamento_dosagem` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `sigla` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
