<?php 
$title = 'Lista de vinculos entre prescrições e indicações';
$this->headTitle($title);
?>
<div class="row">
    <div class="col-md-12">
        <h1><?=$title?></h1>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <form class="form">
            <div class="row">
                <div class="col-md-3">
                    <label>Prescrição</label>
                    <input type="text" name="txt1" class="form-control" >
                </div>
                
                <div class="col-md-3">
                    <label>Indicação</label>
                    <input type="text" name="txt2" class="form-control" >
                </div>
                
                <div class="col-md-3">
                    <label>Duração</label>
                    <input type="text" name="txt3" class="form-control" >
                </div>
                
                <div class="col-md-3" style="position: relative;">
                    <input type="button" name="btnAdd" value="Adicionar" class="btn btn-primary" style="position: absolute; top: 25px;"> 
                </div>
            </div>
        </form>
    </div>
</div>

