<ul class="nav navbar-nav">
<?php foreach ($this->container as $page) : ?>
    <?php $hasChildren = $page->hasPages(); ?>
    
    <?php if (!$hasChildren) : ?>
        <li>
            <a href="<?php echo $page->getHref() ?>">
                <?php echo $this->translate($page->getLabel()) ?>
            </a>
        </li>
    <?php else : ?>
    <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><?php echo $page->getLabel() ?> <b class="caret"></b></a>
        <ul class="dropdown-menu">
            <?php foreach ($page->getPages() as $child) : ?>
                <li>
                    <a href="<?php echo $child->getHref() ?>">
                        <?php echo $this->translate($child->getLabel()) ?>
                    </a>
                </li>
            <?php endforeach; ?>
        </ul>
    </li>
    <?php endif; ?>
<?php endforeach; ?>
</ul>
