<?php
$title = 'Lista de Pássaros';
$this->headTitle($title);
?>
<div class="row">
    <div class="col-md-12">
        <h1><?=$title?></h1>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <table class="table">
            <thead>
                <tr>
                    <th class="col-md-1 text-center">ID</th>
                    <th class="col-md-2 text-center">ID Espécie</th>
                    <th>Nome</th>
                    <th>#</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->passaros as $passaro) : ?>
                <tr>
                    <td class="text-center"><?=$passaro->id?></td>
                    <td class="text-center"><?=$passaro->especie_id?></td>
                    <td><?=$passaro->nome?></td>
                    <td>#</td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>
